management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          ssl: true

server:
  port: ${PORT:8080}
  address: 0.0.0.0

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.hyecuts.loyalty: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile

frontend:
  base-url: ${FRONTEND_BASE_URL:http://localhost:5173}
