spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    # Explicitly set the platform to prevent "Unable to determine Dialect"
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8081}

jwt:
  secret: ${JWT_SECRET:Y2F0Y2hfbWVfaWZfeW91X2Nhbl9oYWNrZXJfYm95XzEyMw==}
  expiration: 86400000 # 24 hours

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY:sk_test_placeholder}
